baseurl = "https://www.patrickbaylis.com/"
title = "Patrick Baylis"
author = "Patrick Baylis"
canonifyurls = true
relativeURLs = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
pagetitle = "Patrick Baylis"
copyright = "© 2021 Patrick Baylis"
copyrightUrl = "https://www.patrickbaylis.com"
faviconfile = "img/favicon-camping.png"
logofile = "img/pbaylis-avatar.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "pbaylis"
twitter = "pbaylis"
linkedin = "pbaylis"
email = "patrick.baylis@ubc.ca"

[[menu.primary]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2
    
[[menu.primary]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 3
    
[[menu.primary]]
    identifier = "CV"
    name = "CV"
    url = "/pdf/Baylis_CV.pdf"
    weight = 4
    
[[menu.primary]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 5

