baseurl = "/"
languageCode = "en-us"
title = "Patrick Baylis"
theme = "hugo-xmin"
googleAnalytics = "UA-167552790-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/pdf/Baylis_CV.pdf"
    weight = 4
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 5
[[menu.main]]
    name = "Sourdough"
    url = "/posts/2020-04-12-bread-notes/"
    weight = 6

[params]
    description = "The professional web home of Patrick Baylis."
    footer = ""
